security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        phpcasts.user.facebook_provider:
            id: phpcasts.facebook.user

    firewalls:
        public:
            # since anonymous is allowed users will not be forced to login
            pattern:   ^/.*
            fos_facebook:
                app_url: "http://apps.facebook.com/phpcasts/"
                server_url: "http://localhost/facebookApp/"
                login_path: /login
                check_path: /loginFb
                default_target_path: /
                provider: phpcasts.user.facebook_provider
            anonymous: true

    access_control:
        - { path: ^/about/.*, role: [ROLE_FACEBOOK] } # This is the route secured with fos_facebook
        - { path: ^/.*, role: [IS_AUTHENTICATED_ANONYMOUSLY] }
